### ISSUE TITLE
账号认证

### ISSUE THREAD

**Issue by xusJs** [gxchain/gxb-box#8]
账号认证，需要审核，审核部分是在哪儿呢？

![image](https://user-images.githubusercontent.com/29571847/43750325-74bfc76e-9a2a-11e8-83b1-6950850b1c98.png)

**Comment by lanhaoxiang** [comment]
你好，
这个项目已过期，已经迁移到des，了解des可以前往开发者中心: developer.gxb.io
DES是面向企业数据交换的需求服务的，全名是Data Exchange Service
